config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes do
    collection do
      get 'filter_by_tag/:tagid' => :filter_by_tag, as: 'filter_by_tag'
      get 'search(/:term)' => :search, as: 'search'
    end
    member do
      put 'favorite'
    end
    resources :recipe_images, only: [:new, :create] do
      collection do
        get 'delete_select'
        put 'delete'
      end
    end
  end
  resources :tags do
    collection do
      get 'search(/:term)' => :search, as: 'search'
    end
  end

  resources :ocr

  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :tags
  has_many_attached :recipe_images

  validates :name, presence: true

  paginates_per 15

  scope :order_by_name, -> { order(Recipe.arel_table[:name].lower, :id) }

  def tag_names
    # Get all related Tags as comma-separated list
    tag_list = []
    tags.each do |tag|
      tag_list << tag.name
    end
    tag_list.join(', ')
  end

  def tag_names=(names)
    logger.info names
    # Delete tag-relations
    self.tags.clear

    # Split comma-separated list
    names = names.split(',').map{ |n| n.strip }.select{ |n| ! n.empty? }

    # Run through each tag
    names.each do |name|
      tag = Tag.find_or_create_by(name: name)
      logger.info tag
      self.tags << tag
    end
  end

  def add_images=(images)
    images.each do |image|
      self.recipe_images.attach(image)
    end
  end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :recipes

  validates :name, uniqueness: true, presence: true

  # tags with at least one recipe
  scope :with_recipes, lambda {
    joins(:recipes)
      .group('id').having('COUNT(recipes.id) > 0')
  }

  # tags with at least one recipe matching the term
  scope :match_term, lambda { |term|
    name_q = Tag.arel_table[:name]
    joins(:recipes)
      .with_recipes
      .where(name_q.matches("%#{term.downcase}%"))
  }

  def self.sort_by_recipe_count(tags)
    tags.sort do |a, b|
      sa = a.recipe_count
      sb = b.recipe_count
      sb <=> sa
    end
  end

  def recipe_count
    recipes.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ocr_controller.rb
class OcrController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def create
    # @recipe = Recipe.find(params[:id])
    # image = @recipe.recipe_images.select{|i| i.id == params[:imgid]}.first
    ri = Recipe.with_attached_recipe_images.find(params[:id]).recipe_images
    image = ri.select { |i| i.id == params[:imgid].to_i }.first
    x1 = params[:x1].to_i
    y1 = params[:y1].to_i
    x2 = params[:x2].to_i
    y2 = params[:y2].to_i
    width = x2 - x1
    height = y2 - y1
    language = params[:language]
    tmp = Tempfile.new('for_rt')
    recognized_text = ''

    begin
      img = MiniMagick::Image.read(image.download)
      img.crop "#{width}x#{height}+#{x1}+#{y1}"
      img.write tmp
      ocrd = RTesseract.new(tmp, processor: 'mini_magick', lang: language)
      # logger.info image.lang
      recognized_text = ocrd.to_s
      logger.info recognized_text
    ensure
      tmp.unlink
    end

    render json: { text: recognized_text }
  end
end

app/controllers/recipe_images_controller.rb
class RecipeImagesController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @page_title = @recipe.name
  end

  def create
    recipe = Recipe.find(params[:recipe_id])

    if params[:image].nil?
      flash[:error] = t('recipes.images.image_missing')
      redirect_to new_recipe_recipe_image_path(recipe) and return
    end

    params[:image].each{ |image|
      if image.content_type == "image/jpeg"
        # downgrade image quality to 60 to reduce size of image
        img = MiniMagick::Image.read(image.read)
        img.quality(60)
        tmpfile = Tempfile.new('img')
        img.write(tmpfile)
        tmpfile.close

        recipe.recipe_images.attach(
          io: tmpfile.open,
          filename: image.original_filename,
          content_type: image.content_type
        )
        tmpfile.unlink
      else
        recipe.recipe_images.attach(image)
      end

    }

    recipe.save

    redirect_to recipe_path(recipe)
  end

  def delete_select
    @recipe = Recipe.find(params[:recipe_id])
    @page_title = @recipe.name
  end

  def delete
    filenames = params[:filenames].split ','
    logger.info filenames
    recipe = Recipe.find(params[:recipe_id])
    images_to_delete = recipe.recipe_images.select{ |i|
      filenames.include?(i.blob.filename.to_s)
    }
    images_to_delete.each{ |i|
      i.purge
    }

    redirect_to recipe_path(recipe)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.order("favorite desc").order_by_name.page params[:page]
  end

  def filter_by_tag
    @recipes = Recipe.joins(:tags).where(tags: { id: params[:tagid] }).page params[:page]
    render 'index'
  end

  def search
    logger.debug "Search recipe for #{params[:term]}"
    # @recipes = Recipe.where(ilike(:name, "%#{params[:term]}"))
    if params[:term].nil?
      @recipes = Recipe.all
    else
      name_q = Recipe.arel_table[:name]
      @recipes = Recipe.where(name_q.matches("%#{params[:term]}%"))
    end

    @recipes = @recipes.page params[:page]

    respond_to do |format|
      format.html { render partial: 'list' }
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    unless @recipe.valid?
      flash.now[:error] = @recipe.errors.messages.map{ |k,v|
        v
      }.join(',')
      render :new and return
    end

    @recipe.save

    redirect_to action: :show, id: @recipe.id
  end

  def show
    @recipe = Recipe.find(params[:id])
    @page_title = @recipe.name
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @page_title = @recipe.name
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update(recipe_params)
    recipe.save
    redirect_to action: :show, id: recipe
  end

  def favorite
    recipe = Recipe.find(params[:id])
    recipe.favorite = !recipe.favorite
    recipe.save
    render json: { redirect_url: recipe_path(recipe.id) }
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy()

    render json: { redirect_url: recipes_path }
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :instructions, :duration, :tag_names, :source)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.with_recipes
    @tags = Tag.sort_by_recipe_count(@tags)
  end

  def search
    @tags =
      if params[:term]
        Tag.match_term(params[:term]).order(:name)
      else
        Tag.sort_by_recipe_count(Tag.with_recipes)
      end

    respond_to do |format|
      format.html { render partial: 'tagslist' }
      format.json { render json: @tags.map(&:name) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ocr_helper.rb
module OcrHelper
end

app/helpers/recipe_images_helper.rb
module RecipeImagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def with_url_links(string)
    md = %r{https?:\/\/[A-Za-z0-9\-\._~:\/\?\#%@!$&'\(\)\+,;\=`\.]+}.match(string)
    return string if md.nil?
    url = md[0]
    front = string[0...md.begin(0)]
    back = string[md.end(0)...string.size]
    "#{front}<a href=\"#{url}\" target=\"_blank\">#{url}</a>#{back}".html_safe
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <% if @page_title %>
      <title><%= "#{@page_title} | #{t('application_title')}"  %></title>
    <% else %>
      <title><%=t 'application_title' %></title>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'styles' %>
  </head>

  <body>
    <%= render :partial => 'shared/navigation' %>
    <%= render :partial => 'shared/messages' %>
    <section class="section">
      <%= yield %>
    </section>
  </body>
</html>

app/views/ocr/_imgregion.html.erb
<div class="columns">
  <div class="column">
    <div class="canvases">
      <canvas 
        id="canvas0"
        class="ocrcanvas" 
        data-target="ocr-selection.canvasImg"
        >
      </canvas>
      <canvas 
        id="canvas1"
        class="ocrcanvas" 
        data-target="ocr-selection.canvasSelect"
        data-action="mousedown->ocr-selection#mousedown mouseup->ocr-selection#mouseup mousemove->ocr-selection#mousemove"
        >
      </canvas>
    </div>
  </div>
  <div class="column">
    <div>
      <div class="select">
        <%= select_tag 'language', options_for_select([[t('ocr.show.lang.deu'), 'deu'], [t('ocr.show.lang.eng'), 'eng']], 'deu'), data: { target: 'ocr-selection.language'} %>
      </div>
      <%= button_tag t('ocr.show.submit'), class: 'button is-primary', data: { action: 'click->ocr-selection#submit'} %>
      <span class="icon has-text-info display_none" data-target="ocr-selection.spinner">
        <i class="fas fa-spinner fa-2x  fa-spin"></i>
      </span>
      <%= button_tag t('ocr.show.toclipboard'), class: 'button is-primary', data: { action: 'click->ocr-selection#toclipboard', target: 'ocr-selection.toclipboardbtn'} %>
      <div class="field">
        <div class="control">
          <%= text_area_tag :recognized, 
                nil, 
                class: 'textarea', 
                placeholder: t('ocr.show.recognized_text_placeholder'), 
                data: { 
                  target: 'ocr-selection.recognizedtext'
                }, 
                rows: 20, 
                autocomplete: 'off' 
          %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ocr/show.html.erb
<div class="container">
  <h1 class="title">
    <%=t 'ocr.show.title' %>
  </h1>
  <h2 class="subtitle">
    <%= @recipe.name %>
  </h2>
  <div data-controller="ocr-selection"  
       data-ocr-selection-id="<%= @recipe.id %>" 
       data-ocr-selection-imgid="<%= @recipe.recipe_images.first.id %>"
       data-ocr-selection-imgurl="<%= rails_blob_path(@recipe.recipe_images.first) %>" 
       data-ocr-selection-ratio="1" 
       data-ocr-selection-ismousedown="false"
       data-ocr-selection-ocrurl="<%= ocr_index_path(:format => :json) %>"
       >
    <% @recipe.recipe_images.each do |image| %>
      <%= image_tag image.variant(resize: "100x100"), class: 'to_delete', data: { 'imgid': image.id, 'imgurl': rails_blob_path(image), action: 'click->ocr-selection#select' } %>
    <% end %>
    <div>
      <%= render :partial => 'imgregion', :locals => { image: @recipe.recipe_images.first } %>
    </div>
  </div>
</div>

app/views/recipe_images/delete_select.html.erb
<div class="container">
  <h1 class="title"><%=t @recipe.name %></h1>
  <h2 class="subtitle">
    <%=t 'action.image_delete' %>
  </h2>
  <div class="delete_images" data-controller="recipeimagesdelete">
    <p class="has-text-info">
      <%=t 'recipes.delete.info' %><br/>&nbsp;
    </p>
    <% @recipe.recipe_images.each do |image| %>
      <%= image_tag image.variant(resize: "100x100"), class: 'to_delete', data: { 'filename': image.filename, action: 'click->recipeimagesdelete#select' } %>
    <% end %>
    <%= form_tag(delete_recipe_recipe_images_path(@recipe), method: :put) do %>
      <%= hidden_field_tag 'filenames', '', { 'data-target': 'recipeimagesdelete.filenames'} %>
      <div class="buttons">
        <%= button_tag t('action.delete'), class: 'button is-danger', disabled: 'true', 'data-target': 'recipeimagesdelete.submitbutton' %>
        <a href="<%= recipe_path(@recipe) %>" class="button"><%=t 'action.cancel' %></a>
      </div>
    <% end %>
  </div
</div>

app/views/recipe_images/new.html.erb
<div class="container">
  <h1 class="title"><%=t @recipe.name %></h1>
  <h2 class="subtitle">
    <%=t 'action.image_add' %>
  </h2>
  <div class="add_image" data-controller="recipeimagesadd">
    <%= form_tag(recipe_recipe_images_path(@recipe), method: :post, multipart: true) do %>
      <div data-target="recipeimagesadd.files">
        <div class="field">
          <div class="control">
            <%= file_field_tag 'image[]', { accept: 'image/*', multiple: true, class: 'input', placeholder: t('recipes.form.placeholder.add_image') } %>
          </div>
        </div>
        <div class="field is-grouped" data-target="recipeimagesadd.buttons">
          <div class="control">
            <%= button_tag t('action.save'), class: 'button is-link' %>
          </div>
          <div class="control">
            <span class="button is-link" data-action="click->recipeimagesadd#add_another">
              <%=t 'action.add_another' %>
            </span>
          </div>
          <div class="control">
            <a href="<%= recipe_path(@recipe) %>" class="button"><%=t 'action.cancel' %></a>
          </div>
        </div>
      </div>
    <% end %>
    <div class="field display_none"  data-target="recipeimagesadd.template">
      <div class="control">
        <%= file_field_tag 'image[]', { accept: 'image/*', multiple: true, class: 'input', placeholder: t('recipes.form.placeholder.add_image') } %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<div class="recipe noSubmitOnEnter" data-controller="recipeform" data-recipeform-url="<%= search_tags_path(term: 'term', format: :json) %>">
  <%= form_for @recipe do |f| %>
    <div class="field">
      <%= f.label :name, class: 'label' %>
      <div class="control">
        <%= f.text_field :name, class: 'input', placeholder: t('recipes.form.placeholder.name') %>
      </div>
    </div>
    <div class="field">
      <%= f.label :ingredients, class: 'label' %>
      <div class="control">
        <%= f.text_area :ingredients, class: 'textarea', placeholder: t('recipes.form.placeholder.ingredients') %>
      </div>
    </div>
    <div class="field">
      <%= f.label :instructions, class: 'label' %>
      <div class="control">
        <%= f.text_area :instructions, class: 'textarea', placeholder: t('recipes.form.placeholder.instructions') %>
      </div>
    </div>
    <div class="field">
      <%= f.label :duration, class: 'label' %>
      <div class="control">
        <%= f.number_field :duration, class: 'input', placeholder: t('recipes.form.placeholder.duration'), autocomplete: 'off' %>
      </div>
    </div>
    <div class="field">
      <%= f.label :tags, class: 'label' %>
      <div class="control">
        <%= f.text_field :tag_names, class: 'input', placeholder: t('recipes.form.placeholder.tags'), 'data-action': 'keyup->recipeform#findtags', 'data-target': 'recipeform.tags', autocomplete: 'off'  %>
      </div>
      <p data-target="recipeform.tagsSuggestion" class="tagsSuggestion">
      </p>
    </div>
    <div class="field">
      <%= f.label :source, class: 'label' %>
      <div class="control">
        <%= f.text_field :source, class: 'input', placeholder: t('recipes.form.placeholder.source'), autocomplete: 'off' %>
      </div>
    </div>
    <div class="field is-grouped">
      <div class="control">
        <%= f.button t('action.save'), class: 'button is-link' %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/_list.html.erb
<ul>
  <% @recipes.each{ |r| %>
    <li>
      <a href="<%= recipe_path(r) %>"><%= r.name %></a>
      <% if r.favorite %> 
        <i class="has-text-primary fas fa-star"></i>
      <% end %>
    </li>
  <% } %>
</ul>

<%= paginate @recipes, window: 2 %>

app/views/recipes/edit.html.erb
<div class="container">
  <h1 class="title">
    <%=t 'recipes.edit' %>
  </h1>
  <%= render partial: 'form' %>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h1 class="title">
    <%=t 'recipes.title' %>
  </h1>
  <div data-controller="search" data-search-url="<%= search_recipes_path %>">
    <div class="field">
      <p class="control has-icons-left">
        <%= text_field_tag :search, nil, class: 'input', placeholder: t('action.search'), autocomplete: 'off',
            'data-action': 'keyup->search#search', 
            'data-target': 'search.term' %>
        <span class="icon is-small is-left">
          <i class="fas fa-search"></i>
        </span>
      </p>
    </div>
    <div class="recipes" data-target="search.list">
      <%= render partial: 'list' %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <h1 class="title">
    <%=t 'recipes.new' %>
  </h1>
  <%= render partial: 'form' %>
</div>

app/views/recipes/show.html.erb
<div class="container" 
     data-controller="recipe" 
     data-recipe-id="<%= @recipe.id %>" 
     data-recipe-url="<%= recipe_path(@recipe, :format => :json) %>" 
     data-recipe-favorite-url="<%= favorite_recipe_path(@recipe, :format => :json) %>" 
     data-recipe-editstate="false">
  <article class="media">
    <figure class="media-left">
      <i class="fas fa-utensils fa-3x"></i>
    </figure>
    <div class="media-content">
      <h1 class="title">
        <%= @recipe.name %>
        <% if @recipe.favorite %> 
          <span>
            <i class="fas fa-star is-size-5 valign-middle has-text-primary"></i>
          </span>
        <% end %>
      </h1>
    </div>
  </article>  
  <div class="ingredients spacetop">
    <p class="subtitle is-3"><%= t('recipes.ingredients') %></p>
    <%= simple_format @recipe.ingredients %>
  </div>
  <div class="instructions spacetop spacebottom">
    <p class="subtitle is-3">
      <%= t('recipes.instructions') %>
      <% if @recipe.duration %>
        <span class="content is-medium paddingleft">
          <%=t 'recipes.show.duration' %>: <%= @recipe.duration %> <%=t 'recipes.show.durationunit' %>
        </span>
      <% end %>
    </p>
    <%= simple_format @recipe.instructions %>
  </div>
  <% unless @recipe.source.nil? || @recipe.source.empty? %>
    <div>
      <p><%= t('recipes.show.source') %>: <%= with_url_links @recipe.source %></p>
    </div>
  <% end %>
  <% unless @recipe.tags.empty? %>
    <div class="recipe_tags">
      <p><span class="prop_fix"><%=t 'recipes.show.tags' %>:</span>
      <% @recipe.tags.each{ |t| %>
        <a href="<%= filter_by_tag_recipes_path(:tagid => t.id) %>">
          <span class="tag is-dark"><%= t.name %></span>
        </a>
      <% } %>
      </p>
    </div>
  <% end %>
  <% if @recipe.recipe_images.count > 0 %>
    <div class="spacetop">
      <% @recipe.recipe_images.each do |image| %>
        <a href="<%= url_for(image) %>">
          <%= image_tag image.variant(resize: "100x100") %>
        </a>
      <% end %>
    </div>
  <% end %>
  <div class="buttons spacetop">
    <a class="button is-success" data-action="click->recipe#toggleeditbuttons">
      <span class="icon">
        <i class="fas fa-caret-right fa-2x" data-target="recipe.editon"></i>
        <i class="fas fa-caret-left fa-2x is-hidden" data-target="recipe.editoff"></i>
      </span>
    </a>
    <a class="button is-info is-hidden" data-action="click->recipe#favorite" data-target="recipe.editbuttons">
      <span class="icon is-small">
        <% if @recipe.favorite %> 
          <i class="fas fa-star"></i>
        <% else %>
          <i class="far fa-star"></i>
        <% end %>
      </span>
    </a>
    <a class="button is-info is-hidden" href="<%= edit_recipe_path @recipe %>" data-target="recipe.editbuttons">
      <span class="icon is-small">
        <i class="fas fa-edit"></i>
      </span>
      <span><%=t 'action.edit' %></span>
    </a>
    <a class="button is-info is-hidden" data-action="click->recipe#deleteDialogShow" data-target="recipe.editbuttons">
      <span class="icon is-small">
        <i class="fas fa-trash"></i>
      </span>
      <span><%=t 'action.delete' %></span>
    </a>
    <a class="button is-info is-hidden" href="<%= new_recipe_recipe_image_path @recipe %>" data-target="recipe.editbuttons">
      <span class="icon is-small">
        <i class="fas fa-camera"></i>
      </span>
      <span><%=t 'action.image_add' %></span>
    </a>
    <% if @recipe.recipe_images.count > 0 %>
      <a class="button is-info is-hidden" href="<%= delete_select_recipe_recipe_images_path @recipe %>" data-target="recipe.editbuttons">
        <span class="icon is-small">
          <i class="fas fa-trash"></i>
        </span>
        <span><%=t 'action.image_delete' %></span>
      </a>
    <% end %>
    <% if @recipe.recipe_images.count > 0 %>
      <a class="button is-info is-hidden" href="<%= ocr_path @recipe %>" data-target="recipe.editbuttons">
        <span class="icon is-small">
          <i class="fas fa-font"></i>
        </span>
        <span><%=t 'action.image_ocr' %></span>
      </a>
    <% end %>
  </div>

  <div class="modal" data-target="recipe.deleteDialog">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="card">
        <div class="card-content">
          <p>
            <%=t 'recipes.delete.are_you_sure' %>
          </p>
          <p>
            <button class="button is-danger"  data-action="click->recipe#delete"><%=t 'yes' %></button>
            <button class="button" data-action="click->recipe#deleteDialogClose"><%=t 'no' %></button>
          </p>
        </div>
      <button class="modal-close is-large" aria-label="close" data-action="click->recipe#deleteDialogClose"></button>
    </div>
  </div>
</div>

app/views/shared/_messages.html.erb
<% if flash[:error] %>
  <section class="section">
    <div class="container">
      <div class="notification is-danger">
        <%= flash[:error] %>
      </div>
    </div>
  </section>
<% end %>
<% if flash[:warning] %>
  <section class="section">
    <div class="container">
      <div class="notification is-warning">
        <%= flash[:warning] %>
      </div>
    </div>
  </section>
<% end %>
<% if flash[:info] %>
  <section class="section">
    <div class="container">
      <div class="notification is-info">
        <%= flash[:info] %>
      </div>
    </div>
  </section>
<% end %>
<% if flash[:success] %>
  <section class="section">
    <div class="container">
      <div class="notification is-success">
        <%= flash[:success] %>
      </div>
    </div>
  </section>
<% end %>

app/views/shared/_navigation.html.erb
<div class="section nospacebottom nospacetop">
  <div class="container">
    <nav class="level is-mobile nospacebottom">
      <!-- Left side -->
      <div class="level-left">
        <div class="level-item">
        </div>
      </div>

      <!-- Right side -->
      <div class="level-right">
        <div class="level-item">
          <div class="buttons">
            <a class="button is-primary" href="<%= recipes_path %>">
              <span class="icon is-small">
                <i class="fas fa-list-ul"></i>
              </span>
            </a>
            <a class="button is-primary" href="<%= new_recipe_path %>">
              <span class="icon is-small">
                <i class="fas fa-plus-square"></i>
              </span>
            </a>
            <a class="button is-primary" href="<%= tags_path %>">
              <span class="icon is-small">
                <i class="fas fa-tags"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/tags/_tagslist.html.erb
<div class="field is-grouped is-grouped-multiline">
  <% @tags.each do |t| %>
    <div class="control">
      <a class="tags has-addons" href="<%= filter_by_tag_recipes_path(:tagid => t.id) %>">
        <span class="tag is-dark"><%= t.name %></span>
        <span class="tag is-info"><%= t.recipes.count %></span>
      </a>
    </div>
  <% end %>
</div>

app/views/tags/index.html.erb
<div class="container">
  <h1 class="title">
    <%=t 'tags.title' %>
  </h1>
  <div data-controller="search" data-search-url="<%= search_tags_path %>">
    <div class="field">
      <p class="control has-icons-left">
        <%= text_field_tag :search, nil, class: 'input', placeholder: t('action.search'), autocomplete: 'off',
            'data-action': 'keyup->search#search', 
            'data-target': 'search.term' %>
        <span class="icon is-small is-left">
          <i class="fas fa-search"></i>
        </span>
      </p>
    </div>
    <div data-target="search.list">
      <%= render partial: 'tagslist' %>
    </div>
  </div>
</div>